---
#
# Installing Java 8
#

# Add the Java repo
# - name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
#   raw: apt-get install python-minimal software-properties-common -y
#   become: true
#   become_user: root
#   become_method: sudo
#   force_apt_get: true


- name: Add the Java PPA repo
  apt_repository:
   repo: ppa:webupd8team/java

# Accept Oracle license

- name: Automatically accept the Oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

# Install Java

- name: Install Java 8
  apt:
   name: openjdk-8-jre-headless
   state: present
   # update_cache: yes
